//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P2_Programacao_Internet
{
    using System;
    using System.Collections.Generic;
    
    public partial class REG_VENDAS
    {
        public int ID { get; set; }
        public int ID_PRODUTOS { get; set; }
        public int QUANTIDADE { get; set; }
        public double VALOR_TOTAL { get; set; }
        public int ID_VENDAS { get; set; }
    
        public virtual PRODUTOS PRODUTOS { get; set; }
        public virtual VENDAS VENDAS { get; set; }
    }
}
